name: Tests
on:
  push:
    branches: [ "main" ]
    paths:
      - ustar.bash
      - test/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: |
          prove -v
